[tool.poetry]
name = "pinecone-datasets"
version = "0.5.0-rc.1"
description = "Pinecone Datasets lets you easily load datasets into your Pinecone index."
authors = ["Pinecone"]
maintainers = [
    "Roy Miara <miararoy@gmail.com>",
]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.8"
polars = "^0.16.4"
pyarrow = "^12.0.0"
fsspec = "^2023.1.0"
gcsfs = "^2023.1.0"
s3fs = "^2023.1.0"
pydantic = "^1.10.5"
protobuf = ">=3.19.3,<3.20.0"
pandas = "^2.0.0"
#pinecone-client = "3.0.0rc2"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.21.1"
pinecone-client = {version="^2.2", extras=["grpc"]}
black = "^23.1.0"
pytest-cov = "^4.0.0"
mypy = "^1.0.1"
pytest = "^7.2.2"
pytest-html = "^3.2.0"
pdoc = "^13.0.0"
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
